FROM node:12-alpine AS release

ARG PHOTOS_PORT=8080
ARG PHOTOS_DIR=/photos
ARG VIDEOS_DIR=/videos
ARG DATA_DIR=/data

WORKDIR /app

COPY package*.json ./

RUN npm install --production

COPY . .

RUN apk add --no-cache ffmpeg

RUN npm run build

ENV PHOTOS_PORT=${PHOTOS_PORT}
ENV PHOTOS_DIR=${PHOTOS_DIR}
ENV VIDEOS_DIR=${VIDEOS_DIR}
ENV DATA_DIR=${DATA_DIR}

EXPOSE ${PHOTOS_PORT}
CMD [ "npm", "run", "start" ]